Use -v for --verbose instead of --version.
LibrePCB/LibrePCB pull request #1063
Opened 2022-11-18 13:40 UTC by ammoniak

Use -v for --verbose instead of --version.
Added -V for --version.

This is my first pull request for this project. Let me know if I missed something :)

Fixes #1008

2022-11-18 13:56 UTC, ubruhin requested changes
Nice, thanks for contributing! :rocket: 

Beside the comment below:
- There are automated tests for the CLI which need to be adjusted as well (I assume CI will currently fail). See directory https://github.com/LibrePCB/LibrePCB/tree/master/tests/cli. Probably only some strings need to be updated, but no test logic.
- Would be great if you could format the code according our coding style. At least on Linux (with Docker) it's dead easy, see instructions [here](https://developers.librepcb.org/df/d24/doc_code_style_guide.html).

Let me know if you need any help. Or if you can't format the code easily, I could push a commit to do so.

2022-11-18 13:56 UTC, ubruhin commented on apps/librepcb-cli/commandlineinterface.cpp
> +  const QCommandLineOption versionOption({"V","version"},tr("Show Version.")); // = parser.addVersionOption();
I'd make the "Version" lowercase for consistency with the rest of the help text. And let's remove the comment to keep it clean :see_no_evil: 

```suggestion
  const QCommandLineOption versionOption({"V","version"},tr("Show version."));
```

2022-11-18 14:06 UTC, ammoniak commented
I will fix the test cases

2022-11-19 14:39 UTC, ubruhin approved these changes
Great, thanks! I added a commit to auto-format the code. Will merge it once CI succeeds :rocket:

2022-11-19 15:58 UTC, merged

2022-11-19 17:17 UTC, ammoniak commented
Thank you. I'll add the auto format to my IDE for the next one.