Improve metainfo file
LibrePCB/LibrePCB pull request #1221
Opened 2023-08-29 19:46 UTC by Alexander-Wilms

The URL types have been used according to https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-url

I've removed to license from the list of features, since it's usually shown in separate badge, like in KDE Discover or on `[Flathub](https://flathub.org/apps/org.librepcb.LibrePCB)`:
![image](https://github.com/LibrePCB/LibrePCB/assets/3226457/5533b3e1-ff7d-48e3-a840-46318a0a0550)

Perhaps the mentioned innovative concepts could be expanded upon.

2023-08-29 21:57 UTC, ubruhin requested changes
Looks great, thanks! Only a small whitespace issue which makes the stylecheck fail.

You can ignore the macOS CI failure, somehow it suddenly stopped working but it's not related to this PR :sob:

2023-08-29 21:57 UTC, ubruhin commented on share/metainfo/org.librepcb.LibrePCB.appdata.xml
> +
These trailing spaces should be removed to make CI happy :see_no_evil:

2023-08-30 08:51 UTC, ubruhin commented
I just saw there's a validation tool for this file and quickly run it:

```
$ appstream-util validate ./share/metainfo/org.librepcb.LibrePCB.metainfo.xml 
./share/metainfo/org.librepcb.LibrePCB.metainfo.xml: FAILED:
• tag-invalid           : <url> type invalid [unknown]
Validation of files failed
```

Any idea what's the exact problem? May it be related to the tool version?

```
$ appstream-util --version
Version:	0.7.18
```

2023-08-30 13:52 UTC, Alexander-Wilms commented
Yes, I think these new URL types are not supported by older versions of appstream-util.
Cf. https://bugzilla.redhat.com/show_bug.cgi?id=1830923

The [Flathub wiki](https://github.com/flathub/flathub/wiki/AppData-Guidelines#use-flathubs-appstream-util) suggests using the flatpak'd version:

```
flatpak install flathub org.freedesktop.appstream-glib
flatpak run org.freedesktop.appstream-glib validate share/metainfo/org.librepcb.LibrePCB.metainfo.xml
share/metainfo/org.librepcb.LibrePCB.metainfo.xml: OK
```

2023-08-30 14:34 UTC, Alexander-Wilms commented
This set of changes is ready to be merged.

Perhaps newer screenshots showcasing the 1.0 GUI using a 16:9 aspect ratio could be added in a separate PR.

2023-08-30 17:56 UTC, merged